# Generated by Django 3.1.1 on 2020-11-27 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название тура')),
                ('image', models.ImageField(upload_to='tours', verbose_name='Изображение')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('short_description', models.TextField(max_length=200, verbose_name='Краткое описание')),
                ('description', models.TextField(null=True, verbose_name='Описание тура')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('currency', models.CharField(max_length=1, verbose_name='Символ валюты')),
                ('category', models.CharField(max_length=200, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='FeaturedTours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website_Natin_Travel.tours')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(max_length=150, verbose_name='Название тура')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
