# Generated by Django 3.1.1 on 2020-11-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Natin_Travel', '0002_auto_20201127_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название ссылки'),
        ),
    ]
