# Generated by Django 3.1.1 on 2020-11-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Natin_Travel', '0004_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='link',
            field=models.SlugField(verbose_name='Название ссылки'),
        ),
    ]
