# Generated by Django 3.1.1 on 2020-11-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Natin_Travel', '0005_auto_20201129_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название ссылки'),
        ),
    ]
