# Generated by Django 3.1.1 on 2020-11-30 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website_Natin_Travel', '0006_auto_20201129_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
