# Generated by Django 3.1.1 on 2020-11-30 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website_Natin_Travel', '0007_auto_20201130_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonimUserApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата заявки')),
                ('tour_title', models.CharField(max_length=150, verbose_name='Название тура')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Анонимная заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='UserApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата заявки')),
                ('tour_title', models.CharField(max_length=150, verbose_name='Название тура')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
